// Job application status choices (matching original Django backend)
const JOB_STATUSES = {
  WISHLIST: 'Wishlist',
  PREPARING: 'Preparing',
  APPLIED: 'Applied',
  ASSESSMENT: 'Assessment',
  INTERVIEW_SCHEDULED: 'Interview_Scheduled',
  INTERVIEW_COMPLETED: 'Interview_Completed',
  OFFER_RECEIVED: 'Offer_Received',
  ACCEPTED: 'Accepted',
  REJECTED: 'Rejected',
  WITHDRAWN: 'Withdrawn',
};

const ALL_STATUS_VALUES = Object.values(JOB_STATUSES);

// Valid status transitions
const VALID_TRANSITIONS = {
  [JOB_STATUSES.WISHLIST]: [JOB_STATUSES.PREPARING, JOB_STATUSES.APPLIED, JOB_STATUSES.WITHDRAWN],
  [JOB_STATUSES.PREPARING]: [JOB_STATUSES.APPLIED, JOB_STATUSES.WITHDRAWN],
  [JOB_STATUSES.APPLIED]: [JOB_STATUSES.ASSESSMENT, JOB_STATUSES.INTERVIEW_SCHEDULED, JOB_STATUSES.REJECTED, JOB_STATUSES.WITHDRAWN],
  [JOB_STATUSES.ASSESSMENT]: [JOB_STATUSES.INTERVIEW_SCHEDULED, JOB_STATUSES.REJECTED, JOB_STATUSES.WITHDRAWN],
  [JOB_STATUSES.INTERVIEW_SCHEDULED]: [JOB_STATUSES.INTERVIEW_COMPLETED, JOB_STATUSES.REJECTED, JOB_STATUSES.WITHDRAWN],
  [JOB_STATUSES.INTERVIEW_COMPLETED]: [JOB_STATUSES.OFFER_RECEIVED, JOB_STATUSES.REJECTED, JOB_STATUSES.WITHDRAWN],
  [JOB_STATUSES.OFFER_RECEIVED]: [JOB_STATUSES.ACCEPTED, JOB_STATUSES.REJECTED, JOB_STATUSES.WITHDRAWN],
  [JOB_STATUSES.ACCEPTED]: [],
  [JOB_STATUSES.REJECTED]: [],
  [JOB_STATUSES.WITHDRAWN]: [],
};

// User roles
const ROLES = {
  USER: 'user',
  ADMIN: 'admin',
};

// Redis key prefixes
const REDIS_KEYS = {
  TOKEN_BLACKLIST: 'token:blacklist:',
  CACHE_APP: 'cache:applications:',
  CACHE_USER_APPS: 'cache:user-apps:',
};

// BullMQ queue names
const QUEUE_NAMES = {
  RESUME_MATCH: 'resume-match',
  RESUME_ANALYZE: 'resume-analyze',
  JOB_FIT: 'job-fit',
  COVER_LETTER: 'cover-letter',
  INTERVIEW_QUESTIONS: 'interview-questions',
  JOB_SUMMARY: 'job-summary',
  CAREER_INSIGHTS: 'career-insights',
};

module.exports = {
  JOB_STATUSES,
  ALL_STATUS_VALUES,
  VALID_TRANSITIONS,
  ROLES,
  REDIS_KEYS,
  QUEUE_NAMES,
};